name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    - name: Run backend tests
      run: |
        cd backend
        pytest
    - name: Run frontend build
      run: |
        cd frontend
        npm run build